<x-layout.app title="Two-Factor Security Verification | Alaa Motors" description="Verify your identity using your secure mobile authentication code.">
    
    <div class="min-h-[60vh] flex items-center justify-center max-w-7xl mx-auto px-6 py-12">
        <div class="w-full max-w-md bg-white rounded-3xl p-8 border border-slate-200/60 shadow-xl space-y-8" 
             x-data="{ recoveryMode: false }">
            
            <div class="text-center">
                <span class="inline-flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 text-luxury-gold mb-3">
                    <svg class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75 11.25 15 15 9.75m-3-7.036-1.523.443a2.25 2.25 0 0 1-1.244 0L6.75 2.25H4.25a.75.75 0 0 0-.75.75v3.315c0 6.621 4.544 12.244 10.5 13.935 5.956-1.691 10.5-7.314 10.5-13.935V3a.75.75 0 0 0-.75-.75h-2.5l-1.983.577a2.25 2.25 0 0 1-1.244 0L12 2.714Z" />
                    </svg>
                </span>
                
                <!-- Code Header -->
                <h1 class="text-2xl font-extrabold text-slate-900 tracking-tight" x-show="!recoveryMode">Verification Code</h1>
                <p class="text-xs text-slate-500 mt-2 max-w-xs mx-auto leading-relaxed" x-show="!recoveryMode">
                    Please confirm access by entering the 6-digit verification code generated by your mobile authenticator app.
                </p>

                <!-- Recovery Header -->
                <h1 class="text-2xl font-extrabold text-slate-900 tracking-tight" x-show="recoveryMode" style="display: none;">Backup Recovery Key</h1>
                <p class="text-xs text-slate-500 mt-2 max-w-xs mx-auto leading-relaxed" x-show="recoveryMode" style="display: none;">
                    Please confirm access by entering one of your emergency recovery codes.
                </p>
            </div>

            <!-- Validation Error Card -->
            @if ($errors->any())
                <div class="rounded-xl bg-rose-50 border border-rose-200 p-4 text-rose-800 text-xs font-semibold leading-relaxed">
                    The security code you entered could not be verified.
                </div>
            @endif

            <form action="{{ route('two-factor.login.store') }}" method="POST" class="space-y-6">
                @csrf

                <!-- Standard Code Input -->
                <div x-show="!recoveryMode">
                    <x-forms.input name="code" 
                                   label="Authenticator App Code" 
                                   placeholder="e.g. 123456" 
                                   autofocus 
                                   inputmode="numeric" />
                </div>

                <!-- Recovery Code Input -->
                <div x-show="recoveryMode" style="display: none;">
                    <x-forms.input name="recovery_code" 
                                   label="Emergency Recovery Code" 
                                   placeholder="e.g. abcde-12345" />
                </div>

                <!-- Toggle Options and Submit -->
                <div class="space-y-4">
                    <button type="submit" class="w-full flex items-center justify-center h-12 rounded-xl text-xs font-bold uppercase tracking-wider bg-luxury-charcoal text-white hover:bg-luxury-gold transition-colors duration-300 shadow-md">
                        Verify Credential
                    </button>
                    
                    <button type="button" 
                            class="w-full text-center text-xs font-bold text-slate-500 hover:text-slate-800 transition-colors uppercase tracking-wider block py-1"
                            @click="recoveryMode = !recoveryMode">
                        <span x-show="!recoveryMode">Use a recovery code</span>
                        <span x-show="recoveryMode" style="display: none;">Use an authenticator code</span>
                    </button>
                </div>
            </form>

        </div>
    </div>
</x-layout.app>
